# Generated by Django 2.2.1 on 2019-05-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_bstore', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
