# Generated by Django 2.1.8 on 2019-05-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_bstore', '0004_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('isbn10', models.CharField(max_length=10)),
                ('author', models.TextField()),
                ('rating', models.FloatField()),
                ('read_url', models.URLField()),
                ('image_url', models.URLField()),
                ('publication_year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='book_table',
        ),
    ]
